### ISSUE TITLE
Add Autoclean feature to Lite Tweaks

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litetweaks#15]
Add new software 'Lite Tasker' to autoclean your system as per frequency eg.
- Never
- Daily
- One a week
- Once a fortnight
- Once a month 

The new code will combine the following tasks:
- Autoremove Packages
- Auto Updates
- Chrome
- Firefox
- Log Archives
- Package Cache
- Thumbnail Cache
- Whisker Menu

via a cronjob or whichever method is more efficient.
There will be a new entry in the main dialogue of Lite tweaks called 'Auto Clean' which will then call parts of the existing scripts and produce a new dialogue with the above frequency choices listed (zenity radio list)

![dge](https://cloud.githubusercontent.com/assets/5382578/7488166/1061521a-f41a-11e4-890f-68a68a64c905.png)

**Comment by Misko-2083** [comment]
It would be ideal if the tasks could be set individually.
![tasking](https://cloud.githubusercontent.com/assets/8826552/7488230/7f115c3a-f3c7-11e4-8a46-6c7bf81b1403.png)

**Comment by linuxlite** [comment]
@Misko-2083 yes, we will need that to appear after a frequency has been chosen, excellent :)

**Comment by Misko-2083** [comment]
Definitely developing a separate application would be easier. Name: Lite Tasker

**Comment by linuxlite** [comment]
@Misko-2083 agreed, great suggestion.
