### ISSUE TITLE
Kernel removal fails to find existing kernels

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litetweaks#35]
Occurs on 32bit system only, 64bit appears to be unaffected.

![kern1](https://cloud.githubusercontent.com/assets/5382578/21129852/85104832-c169-11e6-8148-7f0593afbddd.png)

![kern2](https://cloud.githubusercontent.com/assets/5382578/21129857/89dbcb52-c169-11e6-8d62-abd3f210c416.png)

**Comment by linuxlite** [comment]
Now appearing on 64bit:

![screenshot_2016-12-17_16-12-55](https://cloud.githubusercontent.com/assets/5382578/21284024/b3a74d6e-c473-11e6-9f14-1977f1b4408a.png)

**Comment by ralphys** [comment]
This issue should now be resolved.
