### ISSUE TITLE
Bunching of icons in Hibernate, Suspend

### ISSUE THREAD

**Issue by linuxlite** [linuxlite/litetweaks#75]
Resolution is 1920 x 1080:

![screenshot_2017-03-27_13-23-42](https://cloud.githubusercontent.com/assets/5382578/24336732/a68d1444-12f0-11e7-877e-53982b6afbaf.png)

**Comment by ralphys** [comment]
It looks like you are missing the correct images for that tweak. Let me check on master.

**Comment by linuxlite** [comment]
Ok, I'll check.

**Comment by ralphys** [comment]
I checked on master and the images are there. So either they are not in that system or the wrong permissions are set on /usr/share/liteappsicons/litetweaks/ folder images in your test machine.

![sample](https://cloud.githubusercontent.com/assets/15816320/24336852/a8ce2046-1263-11e7-8916-2a79a1164536.png)

**Comment by linuxlite** [comment]
Confirmed as fine, thanks Ralphy.
